apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mybot
  name: mybot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mybot
  template:
    metadata:
      labels:
        app: mybot
    spec:
      containers:
      - image: winorbit/jensen-bot:latest
        name: mybot
        ports:
        - containerPort: 5000

